### ISSUE TITLE
Broken DNS record for "mapper.polygon.technology" 

### ISSUE THREAD

**Issue by oleggrib** [0xPolygon/polygon-docs#254]
Hello.
I am reading manual how to Map token from Ethereum to Polygon network - https://docs.polygon.technology/pos/how-to/bridging/ethereum-polygon/submit-mapping-request/

Doc says:
In order to map tokens between Ethereum and Polygon PoS, you may use the [Polygon Token Mapper](https://mapper.polygon.technology/).

But `mapper.polygon.technology` DNS record is missing

Could you fix manual or fix DNS record?

Thank you!

**Comment by kmurphypolygon** [comment]
Hi @oleggrib apologies for the confusing, yes, the tool is deprecated and we are about to update this document with the new information. Could you check again in a day or two please to see the updated content please?

Thank you reaching out and feel free to contact us again about any issues you may find.
